# Nano

- hosts: centos
  tasks:
    - name: Install nano
      yum: 
        name: nano
        state: latest

    - name: Enable hilight in nano
      lineinfile: dest=/tmp/ans insertafter="^bar" line="foo"